# Site settings
title: Bookmarks
description: > # this means to ignore newlines until "baseurl:"
  All your favorites in one place.
baseurl: "/bookmarks/" # the subpath of your site, e.g. /blog/
url: "http://duffneubauer.com" # the base hostname & protocol for your site

port: 3000

sass:
  sass_dir: assets/css
  style: :nested

# Build settings
markdown: kramdown
